### ISSUE TITLE
Support pull up bias?

### ISSUE THREAD

**Issue by jnorth** [jcorporation/myGPIOd#4]
Hi there, I don't see a way to set the bias currently. I'm attempting to use the pull up mode for a button attached to a GPIO pin.

As an example, when I run `gpiomon 0 17`, no events are triggered. When I use `gpiomon -B pull-up 0 17`, events are triggered as desired.

See: https://git.kernel.org/pub/scm/libs/libgpiod/libgpiod.git/tree/lib/core.c?h=v1.6.x#n32

**Comment by jcorporation** [comment]
This is currently not implemented, but it should be possible.

Is the bias only needed if the gpio is not pulled up/down through hardware?

**Comment by jnorth** [comment]
Yeah, from what I understand, the Raspberry Pis have built-in resistors to pull up on GPIO pins, but this has to be set using a library ([see here](https://raspberrypi.stackexchange.com/questions/36580/set-pullup-from-command-line)).

The idea being that you can connect a switch directly to a GPIO pin and ground, avoiding the need for a voltage pin and resistor. It's been a bit hard to track down good documentation on this, but [here is an example](https://youtu.be/tCFMmepJjDA?t=297) I've found.

It may be that this should be set system wide at boot or something vs within mygpiod?

**Comment by jcorporation** [comment]
The sysfs interface is deprecated, as far I know. I will look into the gpiomon source, myGPIOd is based on this.

**Comment by jcorporation** [comment]
Bias support is now in devel. Can you test it?
